# Generated by Django 4.2.6 on 2023-11-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
